### ISSUE TITLE
Implement firebase-token-service

### ISSUE THREAD

**Issue by Tzeroxik** [RPG-Portugal/orthanc#9]
# Firebase Token Generator:

Module 'rpg-portugal-firebase-token-service'

1. The module should be a webserver (KTOR) receiving requests with the query param "userId" which should contain a string (no validation required at this point).

2. Should connect to Firebase using a the FirebaseAdminSdk and generate a custom token. (see module 'rpg-portugal-firebase' moduke)

3. Validate an api key (also a uuid) in the HTTP Request's header `X-Api-Key`

4. Should send back relevant HTTP errors correctly

5. The endpoint should be configurable on a json file

The response's body should either contain a field `token` with the generated token or an 'error' and 'message' with the relevant error code and error message

OBS: error codes should be implemented as an enum on 'rpg-portugal-core'

**Comment by Tzeroxik** [comment]
This should be on hold until I finish issue #10

**Comment by Tzeroxik** [comment]
@AWRyder the module 'rpg-portugal-firebase' that your service depends on is done, I've also created the module 'rpg-portugal-firebase-token-service', I left ktor dependencies for you to decide what to import.

**Comment by AWRyder** [comment]
Idea has been deprecated
